# Valores base para LocalStack (entorno de laboratorio en k3s)
# El script tambien refuerza el NodePort para garantizar valor estable.
replicaCount: 1

service:
  type: NodePort
  edgeService:
    port: 4566
    targetPort: 4566
    nodePort: 31566

extraEnvVars:
  #- name: DEBUG
   # value: "1"
  - name: LOCALSTACK_AUTH_TOKEN
    value: ""   #versión Community

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"


# Persistencia habilitada
persistence:
  enabled: true
  size: 1Gi
  storageClass: local-path
  
# Logs más detallados
log:
  level: debug