replicaCount: 1

service:
  type: NodePort
  port: 5000
  nodePort: 31500

persistence:
  enabled: false

deployment:
  strategy:
    type: Recreate

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

configData:
  storage:
    s3:
      region: us-east-1
      bucket: docker-registry-data
      regionendpoint: http://localstack.localstack.svc.cluster.local:4566
      secure: false
      v4auth: true
      forcepathstyle: true
      accesskey: test
      secretkey: test
    delete:
      enabled: true
